public class Constants {
    
    static final Integer DEFAULT_ROWS = 5;
    static final String SELECT_ONE = System.Label.Select_One;
    static final String INVENTORY_LEVEL_LOW = System.Label.Inventory_Level_Low;
    static final List<Schema.PicklistEntry> PRODUCT_FAMILY = Schema.Product2.Family.getDescribe().getPicklistValues();
    static final String DRAFT_ORDER_STATUS = 'Draft';
    static final String ACTIVATED_ORDER_STATUS = 'Activated';
    static final String INVENTORY_ANNOUNCEMENTS = 'Inventory Announcements';
    static final String ERROR_MESSAGE = 'An error has occurred, please take a screenshot with the URL and send it to IT.';
    static final String STANDARD_PRICEBOOK_ID = '01sIY0000001b5XYAQ';

}
